<?php $prdList = $this->getProductToShow(); ?>
<?php 
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
$type = 'widget-product-grid';
$image = 'category_page_grid';
$imageTwo = 'category_page_two_list';
$quickViewHelper = $this->helper('MGS\QuickView\Helper\Data');
?>
<?php if($this->getData('per_row') != null){
	$perRow = $this->getData('per_row');
}else {
	$perRow = $themeSettings['catalog']['per_row'];
} ?>
<?php if($this->getTitle() != ""): ?>
	<div class="title-content margin-bottom50">
		<h2 class="title"><?php echo $this->getTitle(); ?></h2>
	</div>
<?php endif ?>
<?php if(count($prdList) > 0): ?>
	<div id="deal_products" class="owl-carousel deal-carousel products-grid owl-theme<?php if($this->getData('hide_add_to_cart') == 1): ?> hidden-add-cart<?php endif ?>">
		<?php foreach($prdList as $product_id): ?>
			<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); ?>
			<?php $productModel = $objectManager->create('Magento\Catalog\Model\Product'); ?>
			<?php $_product = $productModel->load($product_id); ?>
			<?php $_itemNameStripped = $block->stripTags($_product->getName(), null, true); ?>
			<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>
			<?php $size = $themeHelper->getImageSize(); ?>
			<?php $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();  ?>
			<?php if($this->getSlider() == 1): ?>
				<li class="product-item item">
			<?php else: ?>
				<li class="item <?php echo $themeHelper->getColClass($perRow) ?> <?php echo $themeHelper->getClearClass($perRow, $i) ?>">
			<?php endif ?>
				<div class="product-item-info product-content">
					<div class="product-top">
						<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>" class="product-item-photo">
							<img src="<?php echo $productImage; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive product-image-photo"/>
							<?php if(basename($_product->getData('image')) !=  'no_selection'): ?>
								<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
									<?php $productImageTwo = $_imagehelper->init($_product, $imageTwo)->resize($size['width'], $size['height'])->getUrl(); ?>
									<img src="<?php echo $productImageTwo; ?>" alt="<?php echo $_itemNameStripped ?>" class="img-responsive img-base product-image-photo"/>
								<?php endif ?>
							<?php endif ?>
						</a>
						<?php echo $themeHelper->getProductLabel($_product) ?>
						<ul class="icon-links" data-role="add-to-links">
							<li class="li-quickView"><?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?></li>
							<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
								<li><button data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
								   class="action towishlist" data-action="add-to-wishlist"
								   title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
									<span class="fa fa-heart-o"></span>
								</button></li>
							<?php endif; ?>
							<?php if ($block->getAddToCompareUrl()): ?>
								<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
								<li><button class="action tocompare"
								   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product);?>'
								   title="<?php /* @escapeNotVerified */ echo __('Add to Compare') ?>">
									<span class="fa fa-retweet"></span>
								</button></li>
							<?php endif; ?>
						</ul>
					</div>
					<div class="product-desc product-item-details">
						<div class="cate-name"><?php echo $themeHelper->getCategoryName($_product,$this->getData('title'),'') ?></div>
						<h5 class="product-item-name product-name">
							<a class="product-item-link" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_product) ?>" title="<?php echo $_itemNameStripped ?>"><?php echo $_product->getName() ?></a>
						</h5>
						<div class="prar">
							<?php  echo $block->getProductPrice($_product) ?>
							<?php echo $block->getReviewsSummaryHtml($_product, false, true)?>
						</div>
						<?php echo $this->getLayout()->createBlock('MGS\Mpanel\Block\Products\Deals')->setProduct($_product)->setTemplate('MGS_Mpanel::products/deals/item.phtml')->toHtml(); ?>
						<?php if($this->getData('hide_add_to_cart') != 1): ?>
							<div class="padding-top25">
								<?php if ($_product->isSaleable()): ?>
									<div class="controls"><?php $url = $this->getAddToCartUrl($_product) ?>
									<form data-role="tocart-form" action="<?php echo $url; ?>" method="post">
										<input type="hidden" name="product" value="<?php echo $_product->getId(); ?>">
										<input type="hidden" name="uenc" value="<?php echo $this->getEncodedUrl($url) ?>">
										<?php echo $block->getBlockHtml('formkey')?>
										<button class="tocart btn-icon" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
											<span class="icon"><i class="fa fa-shopping-cart"></i></span>
											<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
										</button>
									</form></div>
								<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
						<?php endif ?>
					</div>
				</div>
			</li>
		<?php endforeach ?>
	</div>
	<?php if($this->getSlider() == 1): ?>
		<script type="text/javascript">
			require([
				'jquery',
				'mgs/owlcarousel'
			], function ($) {
				var owl = $('#deal_products');
				owl.owlCarousel({
					items: <?php echo $perRow ?>,
					autoPlay: false,
					stopOnHover: false,
					nav: <?php if($this->getSliderControl() == 1): ?>true<?php else: ?>false<?php endif ?>,
					navText: ["<i class='fa fa-arrow-left'></i>&nbsp;<span class='text'>BACK</span>","<span class='text'>NEXT</span>&nbsp;<i class='fa fa-arrow-right'></i>"],
					dots: false,
					responsive:{ 0 : {items: 1}, 480 : {items: 1}, 768 : {items: 2}, 991 : {items: 3}, 1200 : {items: <?php echo $perRow ?>} }
				});
			});    
		</script>
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-danger">
		<?php echo __('No deal product to show'); ?>
	</div>
<?php endif ?>