<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Language switcher template
 */
?>

<?php if (count($block->getStores())>1): ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher language switcher-language" data-ui-id="language-switcher" id="switcher-language<?php /* @escapeNotVerified */ echo $id?>">
    
    <div class="actions dropdown options switcher-options">
        <a href="#" class="action toggle switcher-trigger" id="switcher-language-trigger<?php /* @escapeNotVerified */ echo $id?>">
            <span class="view-<?php echo $block->escapeHtml($block->getCurrentStoreCode()) ?>">
               <?php echo $block->escapeHtml($block->getStoreName()) ?>
            </span>
			<i class="fa fa-plus"></i>
        </a>
        <ul class="dropdown switcher-dropdown" style="display:none;"
            data-mage-init='{"dropdownDialog":{
                "appendTo":"#switcher-language<?php /* @escapeNotVerified */ echo $id ?> > .options",
                "triggerTarget":"#switcher-language-trigger<?php /* @escapeNotVerified */ echo $id ?>",
                "closeOnMouseLeave": false,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":null,
				"defaultDialogClass": "dropdown-menu"}}'>
            <?php foreach ($block->getStores() as $_lang): ?>
               
                    <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> switcher-option">
                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getTargetStorePostData($_lang); ?>'>
                             <img src="<?php echo $block->getViewFileUrl('images/flags/'.$block->escapeHtml($_lang->getCode()).'.png');?>" alt=""/><?php echo $block->escapeHtml($_lang->getName()) ?></a>
                    </li>
              
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
