<?php
$params = $this->getRequest()->getParams();
$helper = $this->helper('MGS\Brand\Helper\Data');
$collection = $block->getCollection();
if ($this->getConfig('list_page_settings/small_image_width') != '') {
    $width = $this->getConfig('list_page_settings/small_image_width');
} else {
    $width = 240;
}
if ($this->getConfig('list_page_settings/small_image_height') != '') {
    $height = $this->getConfig('list_page_settings/small_image_height');
} else {
    $height = 180;
}
?>
<div class="shop-by-brand">
    <?php if ($helper->getConfig('list_page_settings/description') != ''): ?>
        <div class="description margin-bottom30">
            <?php echo $helper->getConfig('list_page_settings/description'); ?>
        </div>
    <?php endif; ?>
    <?php if ($helper->getConfig('list_page_settings/show_featured_brands')): ?>
        <?php echo $block->getChildHtml('brand_list_featured'); ?>
    <?php endif; ?>
    <?php echo $block->getChildHtml('brand_search'); ?>
    <?php echo $block->getChildHtml('brand_filter_by_character'); ?>
    <div class="all-brands owl-top-text margin-top50">
        <div class="title-content margin-bottom50">
            <h2 class="title"><span><?php echo __('All brands')?></span></h2>
        </div>
        <?php $flagDigit = false; ?>
        <?php if ($collection->count()): ?>
            <div class="content brands-grid">
                <ul class="brand-list row">
                    <?php $lucian = 0; foreach ($collection as $brand): $lucian++; ?>
                        <?php if (isset($params['char']) && $params['char'] != '' && $params['char'] == '0-9') : ?>
                            <?php $letter = strtoupper(substr($brand->getName(), 0, 1)); ?>
                            <?php if (ctype_digit($letter)): ?>
                                <?php $flagDigit = true; ?>
                                <li class="item brands col-md-custom-5 col-sm-4 col-xs-6 margin-bottom20 <?php if($lucian % 5 == 1): ?> fist-row-item<?php endif ?><?php if($lucian % 3 == 1): ?> row-sm-first<?php endif ?><?php if($lucian % 2 == 1): ?> row-xs-first<?php endif ?>">
									<div class="brand-content">
										<div class="brand-image">
											<a class="brand" style="height: <?php echo $height; ?>px;" title="<?php echo $brand->getName(); ?>"
											   href="<?php echo $brand->getUrl(); ?>">
												<img style="max-height: <?php echo $height; ?>px;" class="brand-small-image"
													 alt="<?php echo $brand->getName(); ?>"
													 src="<?php echo $brand->getSmallImageUrl(); ?>">
											</a>
										</div>
										<?php if ($this->getConfig('list_page_settings/show_brand_name')): ?>
											<div class="feature-brand-title text-center">
												<a class="h6" title="<?php echo $brand->getName(); ?>" href="<?php echo $brand->getUrl(); ?>">
													<?php echo $brand->getName(); ?>
												</a>     
												<?php if ($this->getConfig('list_page_settings/show_product_count')): ?>
													<?php if($block->getProductCount($brand) > 1){ $text = __('items');}else{ $text = __('item');} ?>
													<p><span><?php echo __('(%1 %2)', $block->getProductCount($brand), $text); ?></span></p>
												<?php endif; ?>                                    
											</div>
										<?php endif; ?>
									</div>
                                </li>
                            <?php endif; ?>
                        <?php else: ?>
                            <li class="item brands col-md-custom-5 col-sm-4 col-xs-6 margin-bottom20 <?php if($lucian % 5 == 1): ?> fist-row-item<?php endif ?><?php if($lucian % 3 == 1): ?> row-sm-first<?php endif ?><?php if($lucian % 2 == 1): ?> row-xs-first<?php endif ?>">
								<div class="brand-content">
									<div class="brand-image">
										<a class="brand" style="height: <?php echo $height; ?>px;" title="<?php echo $brand->getName(); ?>"
										   href="<?php echo $brand->getUrl(); ?>">
											<img style="max-height: <?php echo $height; ?>px;" class="brand-small-image"
												 alt="<?php echo $brand->getName(); ?>"
												 src="<?php echo $brand->getSmallImageUrl(); ?>">
										</a>
									</div>
									<?php if ($this->getConfig('list_page_settings/show_brand_name')): ?>
										<div class="feature-brand-title text-center">
											<a class="h6" title="<?php echo $brand->getName(); ?>" href="<?php echo $brand->getUrl(); ?>">
												<?php echo $brand->getName(); ?>
											</a>
											<?php if ($this->getConfig('list_page_settings/show_product_count')): ?>
												<?php if($block->getProductCount($brand) > 1){ $text = __('items');}else{ $text = __('item');} ?>
												<p><span><?php echo __('(%1 %2)', $block->getProductCount($brand), $text); ?></span></p>
											<?php endif; ?>                                   
										</div>
									<?php endif; ?>
								</div>
                            </li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php if (isset($params['char']) && $params['char'] != '' && $params['char'] == '0-9' && $flagDigit == false): ?>
                <script type="text/javascript">
                    require(['jquery'], function ($) {
                        $('ul.brand-list').hide();
                    });
                </script>
                <div class="message">
                    <div class="alert alert-danger"><?php echo __('Have no brands.') ?></div>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <div class="message">
                <div class="alert alert-danger"><?php echo __('Have no brands.') ?></div>
            </div>
        <?php endif; ?>
    </div>
</div>
