<?php
$helper = $this->helper('MGS\Brand\Helper\Data');
$params = $this->getRequest()->getParams();
?>
<div class="search brands-search margin-bottom20 owl-top-text">
	<div class="title-content margin-bottom50">
		<h2 class="title"><?php echo __('Brands Search')?></h2>
	</div>
    <form id="search_brand_form" action="" method="get">
        <div class="form-group">
            <div class="control">
                <input id="search_brand"
                       type="text"
                       name="keyword"
                       value="<?php if (isset($params['keyword'])) {
                           echo $params['keyword'];
                       } ?>"
                       placeholder="<?php echo __('Search brand here...'); ?>"
                       class="input-text form-control"
                       autocomplete="off"/>
                <?php if (isset($params['char']) && $params['char'] != ''): ?>
                    <input id="search_brand_by_char"
                           type="hidden"
                           name="char"
                           value="<?php echo $params['char']; ?>"/>
                <?php endif; ?>
            </div>
        </div>
        <div class="actions">
            <button type="submit"
                    title="<?php echo $block->escapeHtml(__('Search')) ?>"
                    class="action search btn btn-lg btn-primary">
                <span><?php echo __('Search'); ?></span>
            </button>
            <?php if (isset($params['keyword']) || isset($params['char'])): ?>
                <button type="button"
                        onclick="window.location.href='<?php echo $helper->getBrandUrl(); ?>'"
                        title="<?php echo $block->escapeHtml(__('Reset Filter')) ?>"
                        class="action search btn btn-lg btn-secondary margin-left10">
                    <span><?php echo __('Reset Filter'); ?></span>
                </button>
            <?php endif; ?>
			<a class="btn btn-lg btn-primary margin-left10" title="<?php echo __('View All'); ?>" href="<?php echo $helper->getBrandUrl(); ?>"><?php echo __('View All'); ?></a>
        </div>
    </form>
</div>