<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Currency switcher
 *
 * @see \Magento\Directory\Block\Currency
 */
?>
<?php if ($block->getCurrencyCount() > 1): ?>
<?php $currencies = $block->getCurrencies(); ?>
<?php $currentCurrencyCode = $block->getCurrentCurrencyCode(); ?>
<?php $id = $block->getIdModifier() ? '-' . $block->getIdModifier() : ''?>
<div class="switcher currency switcher-currency" id="switcher-currency<?php echo $id?>">   
    <div class="actions dropdown options switcher-options">
        <a href="#" class="action toggle switcher-trigger" id="switcher-currency-trigger<?php echo $id?>">
            <span class="language-<?php echo $block->escapeHtml($block->getCurrentCurrencyCode()) ?>">
               <?php echo $block->escapeHtml($currentCurrencyCode) ?>
            </span>
			<i class="fa fa-plus"></i>
        </a>

        <ul class="dropdown switcher-dropdown" style="display:none;" data-mage-init='{"dropdownDialog":{
            "appendTo":"#switcher-currency<?php echo $id?> > .options",
            "triggerTarget":"#switcher-currency-trigger<?php echo $id?>",
            "closeOnMouseLeave": false,
            "triggerClass":"active",
            "parentClass":"active",
            "buttons":null,
			"defaultDialogClass": "dropdown-menu"}}'>
            <?php foreach ($currencies as $_code => $_name): ?>
               
                    <li class="currency-<?php echo $_code ?> switcher-option">
                        <a href="#" data-post='<?php echo $block->getSwitchCurrencyPostData($_code); ?>'><?php echo $_code ?> - <?php echo $_name ?></a>
                    </li>
               
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<?php endif; ?>
