<?php
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$image1 = 'category_page_grid';
?>
<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_related_products_by_brand')): ?>
        <?php if ($brand = $block->getBrand()): ?>
            <?php
            $_productCollection = $block->getProductCollection();
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            ?>
            <?php if (count($_productCollection)): ?>
                <div class="brand-related-products margin-top40 owl-top-text">
					<div class="title-content margin-bottom30">
						<h3 aria-level="2" role="heading" id="block-heading" class="title"><?php echo $block->getConfig('product_page_settings/title_related_products'); ?></h3>
					</div>
                    <div class="block-content content" aria-labelledby="block-heading">
                        <div class="row products wrapper grid products-grid products-related">
                            <ol id="brand-list-related-products" class="products list items product-items">
                                <?php $iterator = 1; ?>
                                <?php foreach ($_productCollection as $_product): ?>
                                    <li class="item product product-item">
										<div class="product-content">
											<div class="product-top">
												<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
												<?php
													$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
													$size = $themeHelper->getImageSize();
													$productImage = $_imagehelper->init($_product, $image1)->resize($size['width'], $size['height'])->getUrl();
												?>
												<a href="<?php echo $_product->getProductUrl() ?>" class="product-item-photo product-image">
													<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
												</a>
												<ul class="icon-links" data-role="add-to-links">
													<li class="li-quickView">
														<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
													</li>
													<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
														<li><button data-post='<?php echo $block->getAddToWishlistParams($_product); ?>' class="action towishlist" data-action="add-to-wishlist" title="<?php echo __('Add to Wish List') ?>">
															<span><i class="fa fa-heart-o"></i></span>
														</button></li>
													<?php endif; ?>
													<?php if ($block->getAddToCompareUrl()): ?>
														<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
														<li><button class="action tocompare"
														   data-post='<?php echo $compareHelper->getPostDataParams($_product); ?>'
														   data-role="add-to-links"
														   title="<?php echo __('Add to Compare'); ?>">
															<span><i class="fa fa-retweet"></i></span>
														</button></li>
													<?php endif; ?>
												</ul>
											</div>
											<div class="product-desc product-item-details">
												<h5 class="product-item-name product-name">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $block->escapeHtml($_product->getName()) ?>">
														<?php echo $block->escapeHtml($_product->getName()) ?>
													</a>
												</h5>
												<div class="prar"><?php echo $block->getProductPrice($_product); ?></div>
												<div class="controls"><div class="add-to-cart">
													<?php if ($_product->isSaleable()): ?>
														<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
															<button class="action tocart btn-cart btn-icon" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
																<span class="icon"><i class="fa fa-shopping-cart"></i></span>
																<span class="text"><?php echo __('Add to Cart') ?></span>
															</button>
														<?php else: ?>
															<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
															$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
															?>
															<button class="action tocart btn-cart btn-icon"
																	data-post='<?php echo $postData; ?>'
																	type="button" title="<?php echo __('Add to Cart') ?>">
																<span class="icon"><i class="fa fa-shopping-cart"></i></span>
																<span class="text"><?php echo __('Add to Cart') ?></span>
															</button>
														<?php endif; ?>
													<?php else: ?>
														<?php if ($_product->getIsSalable()): ?>
															<div class="stock available"><span><?php echo __('In stock') ?></span></div>
														<?php else: ?>
															<div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
														<?php endif; ?>
													<?php endif; ?>
												</div></div>
											</div>
										</div>
                                    </li>
                                <?php endforeach ?>
                            </ol>
							<script type="text/javascript">
								require([
									'jquery',
									'mgs/owlcarousel'
								], function(jQuery){
									(function($) {
									$("#brand-list-related-products").owlCarousel({
										items : 4,
										lazyLoad : true,
										loop: true,
										nav : true,
										dots : false,
										autoPlay: false,
										stopOnHover: false,
										navText: ["<i class='fa fa-arrow-left'></i>&nbsp;<span class='text'>BACK</span>","<span class='text'>NEXT</span>&nbsp;<i class='fa fa-arrow-right'></i>"],
										responsive:{
											0 : {items: 2}, 480 : {items: 2}, 768 : {items: 3}, 980 : {items: 3}, 1200 : {items: 4}
										}
									});
									})(jQuery);
								});
							</script>
                        </div>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
