<?php $helper = $this->helper('MGS\Blog\Helper\Data'); ?>
<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('sidebar_settings/enabled')): ?>
        <?php if ($block->getConfig('sidebar_settings/show_categories')): ?>
            <?php
            $categories = $block->getCategories();
            ?>
            <?php if (count($categories)): ?>
                <div class="block block-blog-categories">
                    <div class="block-title">
                        <h3 id="block-blog-categories-heading" class="title"><span><?php echo __('Categories') ?></span></h3>
                    </div>
                    <div class="block-content">
                        <ul class="category-list">
                            <?php foreach ($categories as $category): ?>
                                <li class="item">
                                    <div class="category-info">
                                        <a title="<?php echo $category->getTitle(); ?>"
                                           href="<?php echo $category->getCategoryUrl(); ?>">
                                            <?php echo $category->getTitle(); ?>
                                        </a>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($block->getConfig('sidebar_settings/show_recent_posts')): ?>
            <?php
            $collection = $block->getCollection();
            $showThumbnail = $this->getConfig('sidebar_settings/show_thumbnail');
            if ($this->getConfig('sidebar_settings/thumbnail_width') != '') {
                $width = $this->getConfig('sidebar_settings/thumbnail_width');
            } else {
                $width = 80;
            }
            if ($this->getConfig('sidebar_settings/thumbnail_height') != '') {
                $height = $this->getConfig('sidebar_settings/thumbnail_height');
            } else {
                $height = 20;
            }
            ?>
            <?php if ($collection->count()): ?>
                <div class="block block-blog-posts">
                    <div class="block-title">
                        <h3 id="block-blog-posts-heading" class="title"><span><?php echo __('Recent Posts') ?></span></h3>
                    </div>
                    <div class="block-content">
                        <ul class="post-list">
                            <?php foreach ($collection as $post): ?>
                                <li class="item">
                                    <div class="post-img">
                                        <?php if ($showThumbnail): ?>
											<img class="post-thumbnail img-responsive" width="<?php echo $width; ?>"
												 height="<?php echo $height; ?>"
												 alt="<?php echo $post->getTitle(); ?>"
												 src="<?php echo $post->getThumbnailUrl(); ?>"/>
										<a title="<?php echo $post->getTitle(); ?>"
                                           href="<?php echo $post->getPostUrlWithNoCategory(); ?>">
										   <i class="fa fa-search"></i>
                                        </a>
										<?php endif; ?>
                                    </div>
									<div class="post-name">
										<a title="<?php echo $post->getTitle(); ?>"
                                           href="<?php echo $post->getPostUrlWithNoCategory(); ?>">
                                            <?php echo $post->getTitle(); ?>
                                        </a>
										<p><?php echo date('F d Y', strtotime($block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false))) ?></p>
									</div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($block->getConfig('sidebar_settings/show_tags')): ?>
            <?php $tags = $block->getTags(); ?>
            <?php if (count($tags)): ?>
                <div class="block block-blog-tags">
                    <div class="block-title">
                        <h3 id="block-blog-tags-heading" class="title"><span><?php echo __('Tags') ?></span></h3>
                    </div>
                    <div class="block-content tagcloud">
                        <?php
                        $total = 0;
                        foreach ($tags as $tag => $count) {
                            $total += $count;
                        }
                        ?>
                        <?php
                        foreach ($tags as $tag => $count):
                            $percent = floor(($count / $total) * 100);
                            if ($percent < 20):
                                $class = 'smallest';
                            elseif ($percent >= 20 and $percent < 40):
                                $class = 'small';
                            elseif ($percent >= 40 and $percent < 60):
                                $class = 'medium';
                            elseif ($percent >= 60 and $percent < 80):
                                $class = 'large';
                            else:
                                $class = 'largest';
                            endif;
                            ?>
                            <span class="<?php echo $class; ?>">
                                <a title="<?php echo $tag; ?>" href="<?php echo $helper->getTagUrl($tag); ?>"><?php echo $tag; ?></a>
                            </span>
                        <?php endforeach; ?>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
