<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="margin-bottom15">
	<button type="button"
			class="action back btn btn-icon btn-default customization">
		<span class="icon"><i class="fa fa-arrow-up"></i></span>
		<span class="text"><?php /* @escapeNotVerified */ echo __('Go back to product details'); ?></span>
	</button>
</div>