<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
    $_product = $block->getProduct();
?>
<?php if ($_product->isSaleable() && $block->hasOptions()): ?>
<div id="bundleSummary"
     class="block-bundle-summary owl-top-text margin-top40"
     data-mage-init='{"sticky":{"container": ".product-add-form"}}'>
	<div class="title-content margin-bottom20"><h2 class="title"><?php /* @escapeNotVerified */ echo __('Your Customization'); ?></h2></div>
    <div class="content row">
        <div class="bundle-info col-sm-3 col-xs-12">
            <?php echo $block->getImage($_product, 'bundled_product_customization_page')->toHtml(); ?>
        </div>
        <div class="bundle-summary col-sm-9 col-xs-12">
            <div class="product-details product-info-main">
                <strong class="product name h3" style="margin: 0;"><?php echo $block->escapeHtml($_product->getName()) ?></strong>
                <div class="margin-top20">
					<?php if ($_product->getIsSalable()): ?>
						<span class="available stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
							<span><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
						</span>
					<?php else: ?>
						<span class="unavailable stock" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
							<span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
						</span>
					<?php endif; ?>
				</div>
				<h5 class="subtitle"><?php /* @escapeNotVerified */ echo __('Summary'); ?></h5>
				<div id="bundle-summary" data-container="product-summary">
					<ul data-mage-init='{"productSummary": []}' class="bundle items"></ul>
					<script data-template="bundle-summary" type="text/x-magento-template">
						<li>
							<strong class="label"><%- data._label_ %>:</strong>
							<div data-container="options"></div>
						</li>
					</script>
					<script data-template="bundle-option" type="text/x-magento-template">
						<div><?php /* @escapeNotVerified */ echo __('%1 x %2', '<%- data._quantity_ %>', '<%- data._label_ %>') ?></div>
					</script>
				</div>
				<div class="product-add-form" style="padding-top: 30px;">
					<?php echo $block->getChildHtml('', true);?>
				</div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".product-add-form": {
            "slide": {
                "slideSpeed": 1500,
                "slideSelector": "#bundle-slide",
                "slideBackSelector": ".action.customization.back",
                "bundleProductSelector": "#bundleProduct",
                "bundleOptionsContainer": ".product-add-form"
                <?php if ($block->isStartCustomization()): ?>
                ,"autostart": true
                <?php endif;?>
            }
        }
    }
</script>
<?php endif; ?>
