<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
<?php $arFilter = array(); ?>
<div class="filter-current filter-current-1cl">
    <h4 class="block-sub-title filter-current-subtitle" style="color: #222;"
            role="heading"
            aria-level="2"
            data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */ echo __('Now Shopping by') ?></h4>
    <ol class="items row" style="margin-bottom: 0px;">
        <?php foreach ($_filters as $_filter): ?>
			<?php if(!in_array($_filter->getLabel(),$arFilter)): ?>
            <li class="item col-md-3 col-sm-4 col-xs-12 col-xs-half">
                <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?>:</span>
                <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                if ($clearLinkUrl):
                    ?>
                    <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                    </a>
                    <a class="action remove"
                       title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                        <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                    </a>
                <?php else: ?>
                    <a class="action pull-right remove" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                       title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName;?>">
                        <span class="fa fa-trash"></span>
                    </a>
                <?php endif; ?>
            </li>
			<?php $arFilter[] =  $_filter->getLabel(); ?>
			<?php endif ?>
        <?php endforeach; ?>
    </ol>
</div>
<?php endif; ?>
