<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="subcribe-center">
	<div class="block home-subscribe">
		<form class="form subscribe"
			novalidate
			action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
			method="post"
			data-mage-init='{"validation": {"errorClass": "mage-error"}}'
			id="newsletter-validate-detail-center">
			<div class="block-content">
				<div class="field input-box newsletter">
					<div class="control input-box">
						<input class="input-text" name="email" type="email" id="newsletter-center"
									placeholder="<?php /* @escapeNotVerified */ echo __('Sign Up for Our Newsletter...') ?>"
									data-validate="{required:true, 'validate-email':true}"/>
					</div>
				</div>
				<div class="actions">
					<button class="subscribe btn btn-lg btn-primary" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
						<span><?php /* @escapeNotVerified */ echo __('Subscribe!') ?></span>
					</button>
				</div>
			</div>
		</form>
	</div>
</div>
