<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>
<?php
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$image1 = 'category_page_grid';
?>
<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = true;
            $showCompare = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showWishlist = false;
            $showCompare = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItems();

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showWishlist = true;
            $showCompare = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>
	<?php if($type == 'related'): ?>
		<div class="product-list-block owl-bottom-text block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
			<div class="block-title">
				<h3 class="title"  id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><span><?php /* @escapeNotVerified */ echo $title; ?></span></h3>
			</div>
			<div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
				<?php if ($canItemsAddToCart): ?>
					<div class="block-actions">
						<?php /* @escapeNotVerified */ echo __('Check items to add to the cart <br /> or') ?>
						<button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
					</div>
				<?php endif; ?>
				<div class="products wrapper products-list-sidebar products-<?php /* @escapeNotVerified */ echo $type; ?>">
					<?php $len = count($items) ?>
					<div  id="realted-sidebar" class="products list items product-items <?php if($len > 3): ?>owl-carousel<?php endif ?>">
						<?php $iterator = 1; ?>
						<?php $i = 0; foreach ($items as $_item): $i++; ?>
						<?php if($i % 3 == 1): ?><ol class="row"><?php endif ?>
							<?php $available = ''; ?>
							<?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
								<?php if (!$_item->getRequiredOptions()): ?>
									<?php $available = 'related-available'; ?>
								<?php endif; ?>
							<?php endif; ?>
							<?php $_productNameStripped = $block->stripTags($_item->getName(), null, true); ?>
							<?php
								$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
								$size = $themeHelper->getImageSize();
								$ratiomin = $size['width'] / $size['height'];
								$heightMin = 80 / $ratiomin;
								$productImage = $_imagehelper->init($_item, $image)->resize(80, $heightMin)->getUrl();
							?>
							<li class="item col-md-12 col-sm-4 col-xs-12 <?php if($i % 3 == 1): ?>row-sm-first<?php endif ?> <?php if($i % 2 == 1): ?>row-xs-first<?php endif ?>">
								<div class="product-content product-item-info <?php echo $available; ?>">
									<div class="product-left">
										<?php if (!$_item->isComposite() && $_item->isSaleable()): ?>
											<?php if (!$_item->getRequiredOptions()): ?>
												<div class="choice related">
													<input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
												</div>
											<?php endif; ?>
										<?php endif; ?>
										<a class="product-image" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo $block->escapeHtml($_item->getName()) ?>">
											<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
										</a>
									</div>
									<div class="product-right">
										<h6 class="product-name">
											<a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo $block->escapeHtml($_item->getName()) ?>">
												<?php echo $block->escapeHtml($_item->getName()) ?>
											</a>
										</h6>
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
									</div>
								</div>
							</li>
						<?php if($i % 3 == 0 || $i == $len): ?></ol><?php endif ?>
						<?php endforeach ?>
					</div>
					<?php if($len > 3): ?>
						<script type="text/javascript">
							require([
								'jquery',
								'mgs/owlcarousel'
							], function(jQuery){
								(function($) {
								$("#realted-sidebar").owlCarousel({
									items : 1,
									lazyLoad : true,
									nav : true,
									dots : false,
									autoPlay: false,
									stopOnHover: false,
									navText: ["<i class='fa fa-arrow-left'></i>&nbsp;<span class='text'>BACK</span>","<span class='text'>NEXT</span>&nbsp;<i class='fa fa-arrow-right'></i>"],
									responsive:{
										0 : {items: 1}, 480 : {items: 1}, 768 : {items: 1}, 980 : {items: 1}, 1200 : {items: 1}
									}
								});
								})(jQuery);
							});
						</script>
					<?php endif ?>
				</div>
			</div>
		</div>
	<?php else: ?>
	<div class="block <?php if ($type == 'upsell'): ?>margin-top45 owl-top-text<?php endif ?> <?php echo $class; ?>" <?php if ($type == 'upsell'): ?> data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>"<?php endif ?>>
		<div class="title-content margin-bottom30">
			<h3 class="title" id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2">
				<?php /* @escapeNotVerified */ echo $title; ?>
			</h3>
		</div>
		<div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
			<div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $type; ?>">
				<ol id="block-list-<?php echo $block->getId(); ?>" class="owl-carousel-nopadding products block-owl list items product-items">
					<?php $iterator = 1; foreach ($items as $_item): ?>
						<?php $_productNameStripped = $block->stripTags($_item->getName(), null, true); ?>
						<?php
							$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
							$size = $themeHelper->getImageSize();
							$productImage = $_imagehelper->init($_item, $image)->resize($size['width'], $size['height'])->getUrl();
						?>
						<li class="item product product-item product-item-info">
							<div class="product-content">
								<div class="product-top">
									<a class="product-item-photo product-image" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" title="<?php echo $block->escapeHtml($_item->getName()) ?>">
										<img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>
									</a>
									<ul class="icon-links" data-role="add-to-links">
										<li class="li-quickview">
											<?php /* Append Quick View */ ?>
											<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
											<?php echo $quickViewHelper->aroundQuickViewHtml($_item); ?>
										</li>
										<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
											<li><button data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
												<i class="fa fa-heart-o"></i>
											</button></li>
										<?php endif; ?>
										<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
											<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
											<li><button class="action tocompare"
											   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item);?>'
											   data-role="add-to-links"
											   title="<?php /* @escapeNotVerified */ echo __('Add to Compare'); ?>">
												<i class="fa fa-retweet"></i>
											</button></li>
										<?php endif; ?>
									</ul>
								</div>
								<div class="product-desc product-item-details">
									<h5 class="product-item-name product-name">
										<a class="product-name" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>"><?php echo $block->escapeHtml($_item->getName()) ?></a>
									</h5>
									<div class="prar">
										<?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>
										<?php if ($templateType): ?>
											<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true) ?>
										<?php endif; ?>
									</div>
									<?php if ($showCart): ?>
										<div class="controls">
											<?php if ($_item->isSaleable()): ?>
												<?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
													<button class="action tocart btn-icon" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span class="icon"><i class="fa fa-shopping-cart"></i></span>
														<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												<?php else: ?>
													<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
													$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
													?>
													<button class="action tocart btn-icon"
															data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
															type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
														<span class="icon"><i class="fa fa-shopping-cart"></i></span>
														<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
													</button>
												<?php endif; ?>
											<?php else: ?>
												<?php if ($_item->getIsSalable()): ?>
													<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
												<?php else: ?>
													<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
												<?php endif; ?>
											<?php endif; ?>
										</div>
									<?php endif; ?>
								</div>
							</div>
						</li>
					<?php endforeach ?>
				</ol>
				<script type="text/javascript">
					require([
						'jquery',
						'mgs/owlcarousel'
					], function(jQuery){
						(function($) {
						$("#block-list-<?php echo $block->getId(); ?>").owlCarousel({
							items : 4,
							lazyLoad : true,
							loop: true,
							nav : true,
							dots : false,
							autoPlay: false,
							stopOnHover: false,
							margin: 20,
							navText: ["<i class='fa fa-arrow-left'></i>&nbsp;<span class='text'>BACK</span>","<span class='text'>NEXT</span>&nbsp;<i class='fa fa-arrow-right'></i>"],
							responsive:{
								0 : {items: 2}, 480 : {items: 2}, 768 : {items: 2}, 980 : {items: 3}, 1200 : {items: 4}
							}
						});
						})(jQuery);
					});
				</script>
			</div>
		</div>
	</div>
	<?php endif ?>
<?php endif;?>
